# Generated by Django 5.0.6 on 2024-07-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
